spring:
  config:
    import: application-private.yml
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://id.twitch.tv/oauth2/userinfo
            user-name-attribute: preferred_username
            client-name: Twitch
            provider: twitch
        registration:
          twitch:
            provider: twitch
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
