server:
  port: 51160
spring:
  datasource:
    url: jdbc:mysql://10.0.0.196:3306/fm_team_hundo
  security:
    oauth2:
      client:
        registration:
          twitch:
            redirect-uri: "https://hundo.maika.moe/login/oauth2/code/{registrationId}"
ygo:
  apiUrl: https://hundo-api.maika.moe/api
